"""
Listado inicial de efemérides y aniversarios.
Se inserta una sola vez (cuando la tabla está vacía) desde migrate.py.
"""

EFEMERIDES_DATA = [
    {"mes": 1,  "dia": 1,  "tipo": "Efeméride",   "motivo": "Año Nuevo"},
    {"mes": 1,  "dia": 20, "tipo": "Aniversario", "motivo": "Cámara Arbitral de Cereales de Rosario"},
    {"mes": 1,  "dia": 26, "tipo": "Aniversario", "motivo": "CAPA - Círculo Argentino de Periodistas Agrarios"},
    {"mes": 1,  "dia": 28, "tipo": "Efeméride",   "motivo": "Día Mundial de la Acción Frente al Calentamiento Terrestre"},
    {"mes": 1,  "dia": 30, "tipo": "Aniversario", "motivo": "Cámara de Industriales Molineros"},
    {"mes": 2,  "dia": 7,  "tipo": "Efeméride",   "motivo": "Combate de San Lorenzo"},
    {"mes": 2,  "dia": 10, "tipo": "Efeméride",   "motivo": "Día Internacional de las Legumbres"},
    {"mes": 2,  "dia": 12, "tipo": "Aniversario", "motivo": "Liberación y Día Nacional del Estado de Kuwait"},
    {"mes": 2,  "dia": 13, "tipo": "Aniversario", "motivo": "Centro Marítimo de Rosario"},
    {"mes": 2,  "dia": 16, "tipo": "Aniversario", "motivo": "Cámara de Puertos Privados Comerciales"},
    {"mes": 2,  "dia": 16, "tipo": "Aniversario", "motivo": "IDEA"},
    {"mes": 2,  "dia": 16, "tipo": "Aniversario", "motivo": "Asociación de Cooperativas Argentinas"},
    {"mes": 2,  "dia": 16, "tipo": "Aniversario", "motivo": "Asociación Empresaria de Rosario"},
    {"mes": 2,  "dia": 23, "tipo": "Efeméride",   "motivo": "Día del Tambero"},
    {"mes": 2,  "dia": 24, "tipo": "Aniversario", "motivo": "Confederaciones Rurales Argentinas"},
    {"mes": 2,  "dia": 27, "tipo": "Efeméride",   "motivo": "Creación de la Bandera Argentina"},
    {"mes": 2,  "dia": 27, "tipo": "Aniversario", "motivo": "Primer Izamiento de la Bandera Nacional"},
    {"mes": 3,  "dia": 1,  "tipo": "Aniversario", "motivo": "Maizar"},
    {"mes": 3,  "dia": 1,  "tipo": "Efeméride",   "motivo": "Día Nacional del Transporte"},
    {"mes": 3,  "dia": 7,  "tipo": "Efeméride",   "motivo": "Día del Campo"},
    {"mes": 3,  "dia": 8,  "tipo": "Efeméride",   "motivo": "Día Internacional de la Mujer"},
    {"mes": 3,  "dia": 15, "tipo": "Efeméride",   "motivo": "Día del Contratista Rural"},
    {"mes": 3,  "dia": 18, "tipo": "Efeméride",   "motivo": "Día del Ruralista"},
    {"mes": 3,  "dia": 19, "tipo": "Aniversario", "motivo": "Sociedad Rural de Rosario"},
    {"mes": 3,  "dia": 24, "tipo": "Efeméride",   "motivo": "Día de la Memoria, la Verdad y la Justicia"},
    {"mes": 3,  "dia": 26, "tipo": "Aniversario", "motivo": "Sociedad de Acopiadores de Granos de Córdoba"},
    {"mes": 4,  "dia": 2,  "tipo": "Efeméride",   "motivo": "Día del Veterano y de los Caídos en la Guerra de Malvinas"},
    {"mes": 4,  "dia": 12, "tipo": "Aniversario", "motivo": "Primer Embarque de Trigo Argentino"},
    {"mes": 4,  "dia": 15, "tipo": "Aniversario", "motivo": "Cámara de Comercio, Industria y Servicios de San Lorenzo y su Zona"},
    {"mes": 4,  "dia": 19, "tipo": "Aniversario", "motivo": "APOSGRAN"},
    {"mes": 5,  "dia": 1,  "tipo": "Efeméride",   "motivo": "Día Internacional del Trabajador"},
    {"mes": 5,  "dia": 7,  "tipo": "Aniversario", "motivo": "Cámara de Exportadores de Rosario"},
    {"mes": 5,  "dia": 9,  "tipo": "Aniversario", "motivo": "Asociación de Cerealistas de Rosario - ACROS"},
    {"mes": 5,  "dia": 15, "tipo": "Aniversario", "motivo": "Bolsa de Cereales de Buenos Aires"},
    {"mes": 5,  "dia": 17, "tipo": "Aniversario", "motivo": "Día de la Armada Argentina"},
    {"mes": 5,  "dia": 21, "tipo": "Aniversario", "motivo": "Cooperativa de Guillermo Lehmann"},
    {"mes": 5,  "dia": 25, "tipo": "Efeméride",   "motivo": "Instauración del Primer Gobierno Patrio"},
    {"mes": 5,  "dia": 26, "tipo": "Aniversario", "motivo": "Cámara Arbitral de Cereales de la Bolsa de Cereales de Buenos Aires"},
    {"mes": 5,  "dia": 31, "tipo": "Aniversario", "motivo": "Federación Gremial de Comercio e Industria"},
    {"mes": 6,  "dia": 5,  "tipo": "Efeméride",   "motivo": "Día Mundial del Medio Ambiente"},
    {"mes": 6,  "dia": 6,  "tipo": "Aniversario", "motivo": "Cámara Arbitral de Cereales de Entre Ríos"},
    {"mes": 6,  "dia": 7,  "tipo": "Efeméride",   "motivo": "Día del Periodista"},
    {"mes": 6,  "dia": 20, "tipo": "Efeméride",   "motivo": "Día de la Bandera Nacional Argentina"},
    {"mes": 6,  "dia": 25, "tipo": "Efeméride",   "motivo": "Grito de Alcorta / Nacimiento de la Federación Agraria Argentina"},
    {"mes": 6,  "dia": 30, "tipo": "Efeméride",   "motivo": "Día del Molinero"},
    {"mes": 7,  "dia": 2,  "tipo": "Efeméride",   "motivo": "Día de la Agricultura Nacional"},
    {"mes": 7,  "dia": 9,  "tipo": "Efeméride",   "motivo": "Día de la Independencia"},
    {"mes": 7,  "dia": 10, "tipo": "Efeméride",   "motivo": "Día del Comercio"},
    {"mes": 7,  "dia": 10, "tipo": "Aniversario", "motivo": "Bolsa de Comercio de Buenos Aires"},
    {"mes": 7,  "dia": 10, "tipo": "Aniversario", "motivo": "Sociedad Rural Argentina"},
    {"mes": 7,  "dia": 18, "tipo": "Aniversario", "motivo": "Centro de Corredores y Agentes de la Bolsa de Cereales de Buenos Aires"},
    {"mes": 7,  "dia": 26, "tipo": "Aniversario", "motivo": "Argentina Clearing y Registro S.A."},
    {"mes": 8,  "dia": 1,  "tipo": "Aniversario", "motivo": "AAPRESID"},
    {"mes": 8,  "dia": 5,  "tipo": "Aniversario", "motivo": "ADIRA"},
    {"mes": 8,  "dia": 6,  "tipo": "Efeméride",   "motivo": "Explosión edificio calle Salta"},
    {"mes": 8,  "dia": 11, "tipo": "Aniversario", "motivo": "ACSOJA"},
    {"mes": 8,  "dia": 14, "tipo": "Efeméride",   "motivo": "Día del Cerealista"},
    {"mes": 8,  "dia": 15, "tipo": "Aniversario", "motivo": "Unión Industrial de Santa Fe"},
    {"mes": 8,  "dia": 17, "tipo": "Efeméride",   "motivo": "Paso a la Inmortalidad del General José de San Martín"},
    {"mes": 8,  "dia": 17, "tipo": "Aniversario", "motivo": "Federación de Centros y Entidades Gremiales de Acopiadores"},
    {"mes": 8,  "dia": 29, "tipo": "Aniversario", "motivo": "Bolsa de Comercio de Santa Fe"},
    {"mes": 9,  "dia": 1,  "tipo": "Efeméride",   "motivo": "Día del Periodismo Agropecuario"},
    {"mes": 9,  "dia": 2,  "tipo": "Efeméride",   "motivo": "Día de la Industria"},
    {"mes": 9,  "dia": 8,  "tipo": "Efeméride",   "motivo": "Día del Agricultor"},
    {"mes": 9,  "dia": 20, "tipo": "Efeméride",   "motivo": "Día del Perito Clasificador de Cereales, Oleaginosas y Legumbres"},
    {"mes": 9,  "dia": 21, "tipo": "Aniversario", "motivo": "Mesa de Legumbres de Santa Fe"},
    {"mes": 9,  "dia": 23, "tipo": "Aniversario", "motivo": "Bolsa de Comercio de Chaco"},
    {"mes": 9,  "dia": 26, "tipo": "Efeméride",   "motivo": "Día del Empleado de Comercio"},
    {"mes": 9,  "dia": 28, "tipo": "Aniversario", "motivo": "Cámara Arbitral de Aceites Vegetales y Subproductos"},
    {"mes": 10, "dia": 7,  "tipo": "Efeméride",   "motivo": "Día de la Virgen del Rosario"},
    {"mes": 10, "dia": 8,  "tipo": "Efeméride",   "motivo": "Día del Trabajador Rural"},
    {"mes": 10, "dia": 11, "tipo": "Aniversario", "motivo": "Rosgan"},
    {"mes": 10, "dia": 12, "tipo": "Efeméride",   "motivo": "Día del Respeto a la Diversidad Cultural"},
    {"mes": 10, "dia": 15, "tipo": "Efeméride",   "motivo": "Día de las Mujeres Rurales"},
    {"mes": 10, "dia": 16, "tipo": "Aniversario", "motivo": "CIARA y CEC"},
    {"mes": 10, "dia": 16, "tipo": "Aniversario", "motivo": "Bolsa de Cereales y Productos de Bahía Blanca"},
    {"mes": 10, "dia": 26, "tipo": "Aniversario", "motivo": "Sociedad Gremial de Acopiadores de Granos"},
    {"mes": 10, "dia": 29, "tipo": "Efeméride",   "motivo": "Día del Aceitero"},
    {"mes": 11, "dia": 1,  "tipo": "Aniversario", "motivo": "ENAPRO"},
    {"mes": 11, "dia": 3,  "tipo": "Aniversario", "motivo": "Centro de Corredores de Rosario"},
    {"mes": 11, "dia": 4,  "tipo": "Aniversario", "motivo": "Cámara de Actividades Portuarias y Marítimas"},
    {"mes": 11, "dia": 6,  "tipo": "Efeméride",   "motivo": "Día de la Exportación"},
    {"mes": 11, "dia": 9,  "tipo": "Aniversario", "motivo": "Bolsa de Cereales de Córdoba"},
    {"mes": 11, "dia": 10, "tipo": "Efeméride",   "motivo": "Día de la Tradición"},
    {"mes": 11, "dia": 16, "tipo": "Aniversario", "motivo": "Bolsa de Cereales de Entre Ríos"},
    {"mes": 11, "dia": 20, "tipo": "Efeméride",   "motivo": "Día de la Soberanía Nacional"},
    {"mes": 11, "dia": 22, "tipo": "Aniversario", "motivo": "Mercado Argentino de Valores"},
    {"mes": 11, "dia": 22, "tipo": "Aniversario", "motivo": "Centro Entregadores de Cereales, Oleaginosas y Afines - CECOA"},
    {"mes": 12, "dia": 1,  "tipo": "Aniversario", "motivo": "Sociedad de Cerealistas del Norte de PBA"},
    {"mes": 12, "dia": 4,  "tipo": "Aniversario", "motivo": "Rosario Administradora Sociedad Fiduciaria S.A."},
    {"mes": 12, "dia": 5,  "tipo": "Efeméride",   "motivo": "Día Mundial del Suelo"},
    {"mes": 12, "dia": 12, "tipo": "Efeméride",   "motivo": "Día Nacional de la Maquinaria Agrícola"},
    {"mes": 12, "dia": 20, "tipo": "Aniversario", "motivo": "ASAGA"},
    {"mes": 12, "dia": 21, "tipo": "Efeméride",   "motivo": "Día del Estibador Portuario"},
]
