"""
Datos iniciales del módulo Métricas, transcritos de la planilla artesanal
"Métricas totales FBCR.xlsx" (hoja FBCR).

Criterio de carga:
  - Los campos numéricos sólo se llenan cuando el número del Excel es inequívoco.
  - Cuando el dato venía mezclado dentro de texto, o era ambiguo/dudoso, se deja
    el crudo en `notas` y el campo numérico queda en None para no ensuciar los KPI.
  - Las fechas claras van en `fecha`; las difusas ("mayo 2024", "diciembre 2023")
    van en `fecha_texto` y se completa `anio` igual para poder agrupar.

Se siembra una sola vez (ver migrate.seed_metricas_if_empty). A partir de ahí,
las altas nuevas se cargan desde el formulario admin.
"""
from datetime import date


PROGRAMAS = [
    {"slug": "osc", "nombre": "Programa de Aceleración de OSC",
     "descripcion": "Aceleración y acompañamiento a Organizaciones de la Sociedad Civil, junto al Banco de Alimentos de Rosario.",
     "icono": "🤝", "color": "#6366f1", "orden": 1},
    {"slug": "agromakers", "nombre": "Agromakers",
     "descripcion": "Programa de innovación para escuelas técnicas y agrotécnicas de Santa Fe.",
     "icono": "🌱", "color": "#22c55e", "orden": 2},
    {"slug": "empresas", "nombre": "Empresas y Capacitaciones",
     "descripcion": "Talleres, charlas y programas de sostenibilidad dirigidos a empresas e instituciones.",
     "icono": "🏢", "color": "#0ea5e9", "orden": 3},
    {"slug": "educacion-financiera", "nombre": "Educación Financiera",
     "descripcion": "Talleres de educación financiera en escuelas y territorio.",
     "icono": "💰", "color": "#f59e0b", "orden": 4},
    {"slug": "agroindustria", "nombre": "Auxiliar en Agroindustria (UNR)",
     "descripcion": "Tecnicatura/curso de Auxiliar en Agroindustria en convenio con la UNR.",
     "icono": "🎓", "color": "#14b8a6", "orden": 5},
    {"slug": "internos", "nombre": "Programas Internos BCR",
     "descripcion": "Donación de sangre, Nochebuena para todos, equidad y voluntariado de colaboradores BCR.",
     "icono": "❤️", "color": "#ec4899", "orden": 6},
    {"slug": "territorio", "nombre": "BCR en Territorio",
     "descripcion": "Jornadas integrales de la Fundación en localidades de la provincia.",
     "icono": "📍", "color": "#f97316", "orden": 7},
    {"slug": "contingencias", "nombre": "Contingencias y Emergencias",
     "descripcion": "Respuesta solidaria ante inundaciones, COVID-19 y la quema de las islas.",
     "icono": "🆘", "color": "#ef4444", "orden": 8},
]


# Cada dict: programa (slug) + campos de Instancia.
INSTANCIAS = [
    # ---------------------------- OSC --------------------------------------
    {"programa": "osc", "titulo": "1ª Edición", "anio": 2018, "fecha": date(2018, 10, 1),
     "modalidad": "Presencial", "personas": 80, "proyectos": 29, "osc": 30,
     "ganadores": "BAR, Fundación de Neurorehabilitación, La Higuera. Mención: Hoprome, Cotolengo y Fundación Camino.",
     "notas": "No se entregó premio en dinero.", "orden": 1},
    {"programa": "osc", "titulo": "2ª Edición", "anio": 2019, "fecha": date(2019, 7, 1),
     "modalidad": "Presencial", "personas": 117, "proyectos": 25, "osc": 30,
     "ganadores": "Construyendo Puentes, Fonbec, Nidos, Madres caminando en la lucha, Espacio de Igualdad.",
     "notas": "Premios: 1º $60.000 · 2º $50.000 · 3º $40.000.", "orden": 2},
    {"programa": "osc", "titulo": "Réplica en Goya (junto al BAR)", "anio": 2019, "fecha": date(2019, 10, 1),
     "modalidad": "Presencial", "personas": 60, "osc": 30,
     "notas": "No se entregó premio en dinero.", "orden": 3},
    {"programa": "osc", "titulo": "3ª Edición", "anio": 2020, "fecha": date(2020, 3, 1),
     "modalidad": "1 presencial · resto virtual", "personas": 129, "proyectos": 25, "osc": 35,
     "ganadores": "Fundación Emperador, Venezolanos en Rosario, Meraki, Latinoamérica Habla.",
     "notas": "10 charlas online (250 participantes). Programa Fundraising (45 personas). Premios: 1º $60.000 · 2º $50.000 · 3º $40.000.", "orden": 4},
    {"programa": "osc", "titulo": "4ª Edición", "anio": 2021, "fecha": date(2021, 2, 1),
     "modalidad": "Virtual", "personas": 115, "proyectos": 25, "osc": 55,
     "ganadores": "Centro Cultural Funes, La Quinta, Cooperativa María del Rosario, Fundación SM Arcángel, Orillas.",
     "notas": "Programa Fundraising (25 personas). Premios: 1º $100.000 · 2º $80.000 · 3º $60.000.", "orden": 5},
    {"programa": "osc", "titulo": "5ª Edición", "anio": 2021, "fecha": date(2021, 9, 1),
     "modalidad": "Presencial + Zoom", "personas": 89, "proyectos": 17, "osc": 35,
     "ganadores": "Fundación SinRett, Bomberos Voluntarios, Lourdes, La Productora Cooperativa QOM. Mención: Fijando Miradas.",
     "notas": "Premios: 1º $120.000 · 2º $100.000 · 3º $80.000.", "orden": 6},
    {"programa": "osc", "titulo": "6ª Edición", "anio": 2022, "fecha": date(2022, 3, 1),
     "modalidad": "Asincrónico", "personas": 120, "orden": 7},
    {"programa": "osc", "titulo": "7ª Edición", "anio": 2022, "fecha": date(2022, 5, 1),
     "modalidad": "Presencial", "personas": 136, "proyectos": 37, "osc": 97,
     "ganadores": "Cambiando Miradas 2, Gurruchaga, estudiantil vecinal Maradona y ACunar 3, Animalistas Rosario.",
     "notas": "Charla online con valor (75 participantes, 98 inscriptos). Premios: 1º $120.000 · 2º $100.000 · 3º $80.000.", "orden": 8},
    {"programa": "osc", "titulo": "Desafío Redes — 1ª jornada de networking", "anio": 2022, "fecha": date(2022, 12, 1),
     "modalidad": "Presencial", "personas": 180,
     "notas": "Primera jornada de networking con BNI, Fundación Rosario y BAR.", "orden": 9},
    {"programa": "osc", "titulo": "Encuentro de Abordaje Social (x2)", "anio": 2023, "fecha": date(2023, 3, 1),
     "personas": 24, "orden": 10},
    {"programa": "osc", "titulo": "8ª Edición — Programa de Aceleración", "anio": 2023, "fecha": date(2023, 4, 1),
     "modalidad": "Presencial", "personas": 75, "proyectos": 27, "osc": 46, "orden": 11},
    {"programa": "osc", "titulo": "2ª Edición Desafío de Redes", "anio": 2023, "fecha_texto": "diciembre 2023",
     "personas": 190, "notas": "Con BNI, Fundación Rosario, BAR y Defensoría.", "orden": 12},
    {"programa": "osc", "titulo": "Lanzamiento 9na Edición", "anio": 2024, "fecha": date(2024, 2, 1),
     "personas": 290, "proyectos": 45, "orden": 13},
    {"programa": "osc", "titulo": "Repaso Lanzamiento 9na Edición", "anio": 2024, "fecha": date(2024, 2, 1),
     "personas": 34, "orden": 14},
    {"programa": "osc", "titulo": "Final 9na Edición", "anio": 2024, "fecha_texto": "mayo 2024",
     "personas": 212, "proyectos": 42,
     "ganadores": "Ganadores: MUCAR y 3H, FAHOP y Tijeras Solidarias con Cascos Azules, Canción Urgente y proyecto de karaoke. Menciones especiales financiadas por provincia: Nuestra Primera Página, La Higuera, Cambiando Miradas.",
     "notas": "Programa Fundraising. La planilla anota 358 en la columna 'Cantidad de OSC' — valor dudoso (posible acumulado/postulaciones), a revisar.", "orden": 15},
    {"programa": "osc", "titulo": "Laboratorio de Incidencia", "anio": 2024, "fecha_texto": "agosto / septiembre 2024",
     "personas": 60, "orden": 16},
    {"programa": "osc", "titulo": "3ª Edición Desafío de Redes", "anio": 2024, "fecha": date(2024, 12, 1),
     "personas": 120, "orden": 17},
    {"programa": "osc", "titulo": "Taller de Recaudación de Fondos 2025", "anio": 2025, "fecha": date(2025, 7, 1),
     "modalidad": "Presencial", "personas": 148, "orden": 18},
    {"programa": "osc", "titulo": "10° Programa de Aceleración de OSC", "anio": 2025, "fecha": date(2025, 9, 1),
     "personas": 160, "proyectos": 29,
     "ganadores": "Ganadores: Bomberos Voluntarios de Granadero Baigorria, Jóvenes por el Clima – Circular Travesía, Vida Violeta y Casa FAOHP. Menciones: Asociación Civil Sentidos, Universitarios en Acción y Club Atlético María Madre de la Lata.", "orden": 19},
    {"programa": "osc", "titulo": "Consorcio Social", "anio": 2025, "fecha_texto": "2025",
     "notas": "Taller para OSC (en BCR), asistencia en proyectos, generación de fondos para Greencompost, taller ADN emprendedor.", "orden": 20},
    {"programa": "osc", "titulo": "4to Desafío de Redes", "anio": 2025, "fecha": date(2025, 12, 1), "orden": 21},

    # ------------------------- AGROMAKERS ----------------------------------
    {"programa": "agromakers", "titulo": "Ediciones 2019 (3 regionales + 1 provincial)", "anio": 2019,
     "modalidad": "Presencial", "localidades": "Las Toscas, Ceres, Bigand",
     "personas": 560, "proyectos": 70, "mentores": 35,
     "notas": "365 participantes en ediciones regionales + 195 en la provincial. Proyectos: 48 regionales + 22 provincial.", "orden": 1},
    {"programa": "agromakers", "titulo": "Ediciones 2020 (peñas, 2 regionales, Club Agromakers)", "anio": 2020,
     "modalidad": "Virtual", "personas": 235, "proyectos": 42, "mentores": 35,
     "notas": "100 personas (NE) + 135 (NO, Sur y Centro). Proyectos: 15 (NE) + 27 (NO, Sur y Centro).", "orden": 2},
    {"programa": "agromakers", "titulo": "Ediciones 2021 (3 regionales, 1 provincial, 5 Clubes)", "anio": 2021,
     "modalidad": "Virtual + presencial (Rosario) + Convenio LP", "personas": 483, "proyectos": 94, "mentores": 35,
     "ganadores": "Provincial: 5 proyectos premiados.",
     "notas": "137 (Norte) + 91 (Sur) + 100 (Centro y La Pampa) + 120 (provincial). ARN Provincial $1.700.000. Financiamiento investigación Austral 2022.", "orden": 3},
    {"programa": "agromakers", "titulo": "Agromakers Autogestionado Bigand", "anio": 2022,
     "modalidad": "Presencial", "localidades": "Bigand", "personas": 40, "mentores": 5,
     "ganadores": "5 proyectos.", "orden": 4},
    {"programa": "agromakers", "titulo": "1ª Edición Regional Norte", "anio": 2022,
     "modalidad": "Híbrido", "localidades": "Villa Minetti, Bigand, Sa Pereira, San Bernardo",
     "personas": 72, "proyectos": 23, "mentores": 23, "ganadores": "7 proyectos.", "orden": 5},
    {"programa": "agromakers", "titulo": "2ª Edición Regional Norte — Tacuarendí", "anio": 2022,
     "modalidad": "Presencial", "localidades": "Florencia, Villa Guillermina, Las Toscas, Villa Ocampo, Isleta, Paraje San Juan, La Potasa, Colonia Urdaniz, Campo Bello Sur",
     "personas": 270, "proyectos": 45, "mentores": 13, "ganadores": "14 proyectos.",
     "notas": "Club Agromakers junto a Randstad.", "orden": 6},
    {"programa": "agromakers", "titulo": "3ª Edición Regional Sur", "anio": 2022,
     "modalidad": "Híbrido", "localidades": "Chabás, Elortondo, Labordeboy, Aarón Castellanos, Landeta, María Juana, Teodelina, Rosario",
     "personas": 130, "proyectos": 27, "mentores": 8, "ganadores": "8 proyectos.", "orden": 7},
    {"programa": "agromakers", "titulo": "Final Provincial 2022", "anio": 2022,
     "modalidad": "Presencial", "personas": 220, "proyectos": 29, "mentores": 15,
     "ganadores": "1º 'Climate Revolución' (EETP N°363 Norma Aquino, Las Toscas); 2º 'Eco Briq' (EETP N°662 Juan Bautista Cabral, Villa Guillermina); 3º 'Fósforos' (EETP N°300 Colonia Gral. Belgrano, Villa Minetti). Tres menciones.",
     "notas": "ARN Provincial $2.900.000. Aporte Matba Rofex para premios $500.000.", "orden": 8},
    {"programa": "agromakers", "titulo": "Lanzamiento con Docentes", "anio": 2023,
     "modalidad": "Virtual", "personas": 24, "orden": 9},
    {"programa": "agromakers", "titulo": "Formación Maker", "anio": 2023,
     "modalidad": "Virtual", "personas": 40, "orden": 10},
    {"programa": "agromakers", "titulo": "Talleres en escuelas", "anio": 2023,
     "localidades": "San Lorenzo, Maggiolo, Superior de Comercio, Escuela 4 Vientos", "personas": 160, "proyectos": 13,
     "notas": "San Lorenzo: 56 estudiantes/13 proyectos · Maggiolo: 25 · Superior de Comercio: 45 · 4 Vientos: 34.", "orden": 11},
    {"programa": "agromakers", "titulo": "Eventos Regionales 2023", "anio": 2023,
     "modalidad": "Híbrido", "personas": 453, "proyectos": 77,
     "notas": "Regional Centro: 210 personas / 35 proyectos · Regional Sur: 136 / 22 · Regional Norte: 107 / 20.", "orden": 12},
    {"programa": "agromakers", "titulo": "Final Provincial 2023", "anio": 2023,
     "modalidad": "Presencial", "personas": 167, "proyectos": 26, "escuelas": 15, "mentores": 40,
     "ganadores": "1º 'Agrodex' (ropa de trabajo con silobolsas); 2º 'Forraje verde hidropónico'; 3º 'Aquosfera'. Menciones: 'Doña Rosa' (café de soja) y 'Entofusión' (harina de grillos).",
     "notas": "167 estudiantes, 22 docentes, 15 escuelas y 40 mentores. Aportes: $1.500.000 Matba + $8.000.000 CFI. Mentorías con la Universidad Austral (26 instancias).", "orden": 13},
    {"programa": "agromakers", "titulo": "Encuentro con Escuelas de Rosario", "anio": 2023,
     "modalidad": "Presencial", "personas": 51, "orden": 14},
    {"programa": "agromakers", "titulo": "Formación Makers II", "anio": 2023,
     "modalidad": "Virtual", "personas": 75, "orden": 15},
    {"programa": "agromakers", "titulo": "Lanzamiento 2024 (provincia + Rosario)", "anio": 2024,
     "modalidad": "Virtual", "personas": 58,
     "notas": "20 personas (provincia) + 38 (Rosario).", "orden": 16},
    {"programa": "agromakers", "titulo": "Agromakers edición Rosario", "anio": 2024,
     "modalidad": "Presencial", "personas": 170, "escuelas": 14,
     "notas": "14 escuelas; 170 entre estudiantes, docentes y directivos.", "orden": 17},
    {"programa": "agromakers", "titulo": "Visitas territoriales (Rosario, Norte y Sur)", "anio": 2024,
     "modalidad": "Presencial",
     "notas": "Rosario: la planilla anota '5 518 estudiantes y 24 docentes' (cifra a verificar). Región Sur: Cafferata, Chabás (93 est./19 proy.), Los Quirquinchos (54 est./12 proy.). Región Norte: Villa Minetti (64/12), Ceres (85/17), La Potasa (48), Tacuarendí (57/12).", "orden": 18},
    {"programa": "agromakers", "titulo": "Talleres y ediciones locales 2025 (Sur, Norte, Centro)", "anio": 2025,
     "modalidad": "Presencial",
     "notas": "Región Sur: 12 visitas. Regiones Norte y Centro: talleres y ediciones locales. Formación Makers para docentes (virtual).", "orden": 19},

    # -------------------------- EMPRESAS -----------------------------------
    {"programa": "empresas", "titulo": "Capacitaciones 2018–2019", "anio": 2019, "personas": 2100,
     "notas": "Talleres Quiero Ser B, Camino +B, UNR Emprende, BCR Capacita (sostenibilidad, CO2, transición energética, huella de carbono), charlas inspiracionales, FEXA, INTA, búsqueda de empleo, ABC Desarrollo de Fondos, Vorterix, paneles UNR, Aricana, Warecloud, entre otros.", "orden": 1},
    {"programa": "empresas", "titulo": "Capacitaciones 2020", "anio": 2020, "personas": 1790, "orden": 2},
    {"programa": "empresas", "titulo": "Capacitaciones 2021", "anio": 2021, "personas": 2600, "orden": 3},
    {"programa": "empresas", "titulo": "Capacitaciones 2022", "anio": 2022, "personas": 797,
     "notas": "Toque de Campana, Congreso Mujeres Líderes (Ceres), TecnoAgro Bigand, Reporte y Programa de Sostenibilidad, ROSGAN, TEDX, Día B, Vital Voices, Lab POTENCIAR, entre muchos otros. (La columna 'participantes' registra 797; el detalle lista bastantes más, a revisar.)", "orden": 4},
    {"programa": "empresas", "titulo": "Capacitaciones 2023", "anio": 2023,
     "notas": "Taller UNICEF (170), Nuevos Liderazgos (60), Toque de Campana (80), UCA Nuevas Economías (27), Conectividad Rural CAA (80), Ciclo de Sostenibilidad, Ashoka Cono Sur (46+36), Mujeres Rurales (40), UNICEF Lactancia (100), AIM (30), Global Shapers (25), OIT (34), Agrarias (150), Neobiz (70), entre otros. (Sin total consolidado en la planilla.)", "orden": 5},
    {"programa": "empresas", "titulo": "Capacitaciones 2024", "anio": 2024,
     "notas": "Toque de Campana (159), Ciclo de Sostenibilidad (92), Diplomatura Innovación Social UCA (22), Formación de Dirigentes Empresariales (20), Ashoka (80), CIMPAR (58), Charla Ateneos (52), Mujeres en Finanzas (60), Reportes de Sostenibilidad (62), Espacios Laborales Equitativos (250).", "orden": 6},
    {"programa": "empresas", "titulo": "Capacitaciones 2025", "anio": 2025,
     "notas": "Toque de Campana (120), Charla Co-Creando Futuro (320), Diplomatura UCA, FNGA, Sostenibilidad con asociados (65), La Cumbre, CEIDA, UAI, Centro de Corredores, evaluación de proyectos de impacto UCA, Lanzamiento CEIDA UNICEF, entre otros.", "orden": 7},

    # ---------------------- EDUCACIÓN FINANCIERA ---------------------------
    {"programa": "educacion-financiera", "titulo": "Educación Financiera 2025", "anio": 2025, "personas": 1077,
     "localidades": "Gral. Lagos, San Lorenzo, Bigand, Firmat, Casilda, Zavalla, Villa Mugueta, Juncal, Máximo Paz, Rosario, María Juana, Las Toscas, Alcorta",
     "notas": "Incluye BCR en Territorio, expos de carreras, ferias del libro, escuelas y diplomaturas (UCA).", "orden": 1},

    # ------------------------ AGROINDUSTRIA UNR ----------------------------
    {"programa": "agroindustria", "titulo": "Cohorte 2023 (presencial)", "anio": 2023,
     "modalidad": "Presencial", "personas": 40, "proyectos": 37,
     "notas": "60 inscriptos, finalizaron 40, 37 proyectos.", "orden": 1},
    {"programa": "agroindustria", "titulo": "Cohorte 2024 (virtual)", "anio": 2024,
     "modalidad": "Virtual", "personas": 40,
     "notas": "150 inscriptos, finalizaron 40.", "orden": 2},
    {"programa": "agroindustria", "titulo": "Cohorte 2024 (presencial)", "anio": 2024,
     "modalidad": "Presencial", "personas": 87,
     "notas": "150 inscriptos, finalizaron 87 estudiantes.", "orden": 3},
    {"programa": "agroindustria", "titulo": "Cohorte 2025 (presencial)", "anio": 2025,
     "modalidad": "Presencial", "personas": 160,
     "notas": "400 inscriptos, 250 iniciaron, finalizaron 160.", "orden": 4},

    # -------------------------- INTERNOS BCR -------------------------------
    {"programa": "internos", "titulo": "Donación de Sangre", "anio": 2019,
     "notas": "2019–2022: 1ª edición (70 inscriptos), 2ª edición (40). 2023: edición diciembre (21 personas). 2024: edición realizada.", "orden": 1},
    {"programa": "internos", "titulo": "Nochebuena para Todos", "anio": 2019,
     "notas": "Cajas navideñas: 2019 (35) · 2021 (32) · 2022 (34) · 2023 (27) · 2024 (14).", "orden": 2},
    {"programa": "internos", "titulo": "Espacios Laborales e Institucionales Equitativos", "anio": 2021,
     "personas": 60, "notas": "60 líderes (directores, gerentes, jefes y coordinadores). Consejo de Administración FBCR, Comisión de RRHH, 30 referentes de comisiones BCR.", "orden": 3},
    {"programa": "internos", "titulo": "Espacios Laborales Equitativos 2022", "anio": 2022,
     "notas": "Consejo Ejecutivo Matba Rofex (6), Gerentes y Directores (21), CAA (35), Warecloud (12), CAC (7), Bolsa de Santa Fe (25), Argenway (25), entre otros.", "orden": 4},
    {"programa": "internos", "titulo": "Voluntariado Primera Experiencia FBCR (AMAP)", "anio": 2022,
     "personas": 20, "notas": "20 colaboradores BCR + voluntarios de la entidad.", "orden": 5},
    {"programa": "internos", "titulo": "Espacios Laborales Equitativos 2023", "anio": 2023,
     "personas": 723, "notas": "Pirelli (150), El Potrero (30), Concesionarios (75), encuentros con colaboradores (270), Matba Rofex (64), MAV (134).", "orden": 6},
    {"programa": "internos", "titulo": "Espacios Laborales Equitativos 2024", "anio": 2024,
     "notas": "Repaso interno (+30). Segunda edición del programa.", "orden": 7},

    # -------------------------- TERRITORIO ---------------------------------
    {"programa": "territorio", "titulo": "Venado Tuerto", "anio": 2023, "localidades": "Venado Tuerto", "orden": 1},
    {"programa": "territorio", "titulo": "Las Parejas", "anio": 2024, "localidades": "Las Parejas",
     "notas": "Talleres Agromakers (243 estudiantes), taller OSC (34 actores de la sociedad civil).", "orden": 2},
    {"programa": "territorio", "titulo": "Cañada de Gómez", "anio": 2024, "localidades": "Cañada de Gómez", "orden": 3},
    {"programa": "territorio", "titulo": "El Trébol", "anio": 2024, "localidades": "El Trébol", "personas": 400,
     "notas": "Taller de inserción laboral y educación financiera (60 estudiantes), taller OSC (30 actores).", "orden": 4},
    {"programa": "territorio", "titulo": "General Lagos", "anio": 2025, "localidades": "General Lagos", "orden": 5},
    {"programa": "territorio", "titulo": "San Lorenzo", "anio": 2025, "localidades": "San Lorenzo", "personas": 290, "orden": 6},
    {"programa": "territorio", "titulo": "Casilda", "anio": 2025, "localidades": "Casilda", "personas": 600, "orden": 7},
    {"programa": "territorio", "titulo": "Alcorta", "anio": 2025, "localidades": "Alcorta", "personas": 433, "orden": 8},

    # ------------------------- CONTINGENCIAS -------------------------------
    {"programa": "contingencias", "titulo": "Inundaciones en el Norte Santafesino", "anio": 2019,
     "notas": "Abordaje junto al INTA: leche, aires acondicionados, kits sanitarios y productivos para pequeños productores (Villa Minetti, El Nochero, Paraje Las Quinientas). Paraje San Juan: aljibes y trabajo sobre infraestructura, género y desarrollo socioproductivo. Se armó un protocolo de abordaje de contingencias para OSC.",
     "reconocimiento": "Reconocimiento provincial por las acciones solidarias: https://bcrnews.com.ar/bcr-platinum/el-gobierno-de-santa-fe-reconocera-a-fundacion-bcr-por-sus-acciones-solidarias/", "orden": 1},
    {"programa": "contingencias", "titulo": "COVID-19 — Campaña Contagiemos Solidaridad", "anio": 2020,
     "notas": "Co-organizada por BAR y BCR con Municipalidad, Provincia, Concejo, UNR, Cáritas y otras. Resultados: 5.462.329 kg de alimentos entregados, 1.634 organizaciones beneficiarias, 394.161 personas alcanzadas, 260 ollas barriales, 178 donantes y $189.772.210 recaudados.",
     "reconocimiento": "Diploma de Honor del Concejo Municipal de Rosario. https://youtu.be/M8zn1jFcz0Q", "orden": 2},
    {"programa": "contingencias", "titulo": "Quema de las islas", "anio": 2020,
     "notas": "Proyecto de desarrollo de comunidad articulado con INTA, Facultad de Ciencias Agrarias (UNR), Amigos del Río, Mundo Aparte, Asociación Santafesina de Remo, Rotary Capitán Bermúdez y clubes de la costa, con aval municipal y provincial de Santa Fe y Entre Ríos.",
     "reconocimiento": "https://www.bcr.com.ar/es/sobre-bcr/medios/noticias/lanzan-un-plan-de-forestacion-en-las-islas-como-respuesta-los-incendios", "orden": 3},
]
